with open('generatedcodeCase.txt', 'w') as f:
    f.write('case (schakelaar.q){\n\t')
    for i in range(50):
        s = i*2
        f.write(f'{i}:')
        f.write('\n\t\t')
        f.write('case (signalSel.q){')
        f.write('\n\t\t')
        f.write('1:')
        f.write('\n\t\t\t')
        f.write(f'iopin[{s}] = 0; iopin[{s+1}] = 0;')
        f.write('\n\t\t')
        f.write('2:')
        f.write('\n\t\t\t')
        f.write(f'iopin[{s}] = 0; iopin[{s+1}] = 1;')
        f.write('\n\t\t')
        f.write('3:')
        f.write('\n\t\t\t')
        f.write(f'iopin[{s}] = 1; iopin[{s+1}] = 0;')
        f.write('\n\t\t')
        f.write('4:')
        f.write('\n\t\t\t')
        f.write(f'iopin[{s}] = 1; iopin[{s+1}] = 1;')
        f.write('\n\t\t}\n\t')
    f.write('}')